/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import basicClasses.Course;
import basicClasses.Degree;
import basicClasses.Student;
import dataManagement.SystemData;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JFrame;

/**
 *
 * @author Sandeep
 */
public class StudentReport extends javax.swing.JPanel {
    JFrame  panelHolder;
    SystemData systemData;
    /**
     * Creates new form ImportStudent
     */
    public StudentReport(JFrame  panelHolder, SystemData systemData) {
        this.panelHolder = panelHolder;
        this.systemData = systemData;  
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        degreePlanButton = new javax.swing.JButton();
        studentCourseButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student Report");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        degreePlanButton.setText("View Degree Plan Report");
        degreePlanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degreePlanButtonActionPerformed(evt);
            }
        });

        studentCourseButton.setText("View Student-Course Report");
        studentCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentCourseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(degreePlanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(studentCourseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(degreePlanButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(studentCourseButton)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel2, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void degreePlanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degreePlanButtonActionPerformed
        System.out.println("--Degree Plan Report--");
        System.out.println("Degree   NumberOfStudent(Existing+Forecasted)");
        Object columnNames[] = {"Degree", "Number of Student"};
        HashSet<Degree> degrees = new HashSet(systemData.getDegrees().values());        
        Object rowData[][] = new Object[degrees.size()][2];
        int i = 0;
        for(Degree degree: degrees){       
            rowData[i][0] = degree;
            System.out.print(degree+"  ");
            int noOfStudents = 0;
            Iterator<Map.Entry<Student, HashSet<Course>>> entrySetIt= 
                    systemData.getSchedule().consolidatedStudentCourse.entrySet().iterator();
            while(entrySetIt.hasNext()){
                Student student = entrySetIt.next().getKey();
                if(student.getMajor().equals(degree)){
                    ++noOfStudents;
                }                    
            }
            System.out.println(noOfStudents); 
            rowData[i][1] = noOfStudents;
            ++i;
        }        
        panelHolder.setTitle("Degree Plan Report");
        panelHolder.getContentPane().removeAll();
        panelHolder.getContentPane().add(new ViewReport(panelHolder, systemData, "StudentReport",
                "Degree Plan Report", rowData, columnNames));
        panelHolder.getContentPane().revalidate(); 
    }//GEN-LAST:event_degreePlanButtonActionPerformed

    private void studentCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentCourseButtonActionPerformed
        System.out.println("--Student-Course Report--");
        System.out.println("Student   #courseCompleted #courseNeededToGraduate");
        Object columnNames[] = {"Student", "No. of Course Completed", "No. of Course Needed to Graduate"}; 
        Iterator<Map.Entry<Student, HashSet<Course>>> entrySetIt= 
                systemData.getSchedule().consolidatedStudentCourse.entrySet().iterator();       
        Object rowData[][] = new Object[systemData.getSchedule().consolidatedStudentCourse.size()][3];
        int i = 0;
        while(entrySetIt.hasNext()){            
            Student student = entrySetIt.next().getKey();       
            rowData[i][0] = student;   
            rowData[i][1] = systemData.getSchedule().studentToNoOfCoursesTaken.get(student);   
            rowData[i][2] = systemData.getSchedule().studentToNoOfCoursesNeededToGrad.get(student);
            ++i;
            System.out.print(student+"  ");         
            System.out.print(systemData.getSchedule().studentToNoOfCoursesTaken.get(student) + "  ");         
            System.out.println(systemData.getSchedule().studentToNoOfCoursesNeededToGrad.get(student));
        }        
             
        panelHolder.setTitle("Student-Course Report");
        panelHolder.getContentPane().removeAll();
        panelHolder.getContentPane().add(new ViewReport(panelHolder, systemData, "StudentReport",
                "Student-Course Report", rowData, columnNames));
        panelHolder.getContentPane().revalidate(); 
    }//GEN-LAST:event_studentCourseButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton degreePlanButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton studentCourseButton;
    // End of variables declaration//GEN-END:variables
}
